//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Elmish Land (v0.1.25).
// 
//     Here are the available commands:
// 
//     elmish-land init <project-dir> ............. create a new project
//     elmish-land server <working-directory> ... run a local dev server
//     elmish-land build ................. build your app for production
//     elmish-land add page <url> ....................... add a new page
//     elmish-land add layout <name> .................. add a new layout
//     elmish-land routes .................. list all routes in your app
// 
//     Want to learn more? Visit https://github.com/reaptor/elmish-land
//     
// This file will be overwritten when re-executing
// 'elmish-land server' or 'elmish-land build'.
// </auto-generated>
//------------------------------------------------------------------------------
module GittyGUI.Routes

open Feliz.Router

[<RequireQualifiedAccess>]
type Route =
    | Home
    | NotFound

module Route =
    let asUrl =
        function
        | Route.Home  -> $"/"
        | Route.NotFound -> "notFound"

    let parse (xs: string list) =
        match xs |> List.map (fun x -> x.ToLowerInvariant ()) with
        | []
        | [] -> Route.Home 
        | other ->
            printfn "Route not found: '%A'" other
            Route.NotFound
